---
title: "datavis"
author: "Olga Chyzh"
date: "February 19, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE,fig.cap = "...")
```

Libraries:
```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(maps)
library(mapdata)
library(lubridate)
library(leaflet)
library(tidyverse)
library(magrittr)
library(usmap)
library(mapproj)

```


Open the data:
```{r}
rm(list=ls())
trumpilot<-read.csv("soydata.csv", header=TRUE)
## Generate measure of vote shift
trumpilot$votech <- with(trumpilot, log(Rep18*Dem16/(Rep16*Dem18)))
#trumpilot<-subset(trumpilot, is.finite(votech)) #Do we want to throw out all cases in which a major party candidate ran unopposed by the other major party candidate?

## Generate state variable for state fixed effects
trumpilot$statefips <- as.factor(floor(trumpilot$FIPS/1000))

trumpilot<-trumpilot %>% mutate(subregion=tolower(str_remove(county, " County")), region=tolower(state_name)) 
trumpilot$soyval12v1<-with(trumpilot, 100*sales_USD/(GDP2012*1000))

```





Maps:
```{r}
counties <- map_data("county") #map_data function is under the ggplot2 package. 
p <- ggplot() +
  geom_polygon(data=counties, aes(x=long, y=lat, group=group), fill="grey85", color="white")
#geon_polygon is making the base boarder for world map. By assigning group, we make R draw lines only withing each country.
p

states<-map_data("state")

usamap <- p+
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())
#We made better map without grey background and useless longitude and latitude axes.
usamap

#usamap + coord_map("albers",lat0=39, lat1=45)
#usamap + coord_map("mercator")
#usamap + coord_map("gilbert")
#usamap + coord_map("stereographic")
#usamap + coord_map("cylindrical")
#usamap + coord_map("azequalarea")


```

Merge with data:
```{r}
counties$subregion<-str_remove(counties$subregion," county")
trumpilot$subregion<-str_remove(trumpilot$subregion," county")
trumpilot$subregion<-str_remove(trumpilot$subregion," parish")
trumpilot$subregion[trumpilot$subregion=="dekalb"]<-"de kalb"
trumpilot$subregion[trumpilot$subregion=="desoto"]<-"de soto"
trumpilot$subregion[trumpilot$subregion=="dewitt"]<-"de witt"
trumpilot$subregion[trumpilot$subregion=="dupage"]<-"du page"
trumpilot$subregion[trumpilot$subregion=="hampton city"]<-"hampton"
trumpilot$subregion[trumpilot$subregion=="lamoure"]<-"la moure"
trumpilot$subregion[trumpilot$subregion=="laporte"]<-"la porte"
trumpilot$subregion[trumpilot$subregion=="lasalle"]<-"la salle"
trumpilot$subregion[trumpilot$subregion=="newport news city"]<-"newport news"
trumpilot$subregion[trumpilot$subregion=="norfolk city"]<-"norfolk"
trumpilot$subregion[trumpilot$subregion=="o'brien"]<-"obrien"
trumpilot$subregion[trumpilot$subregion=="prince george's"]<-"prince georges"
trumpilot$subregion[trumpilot$subregion=="queen ann's"]<-"queen anns"
trumpilot$subregion[trumpilot$subregion=="suffolk city"]<-"suffolk"
trumpilot$subregion[trumpilot$subregion=="virginia beach city"]<-"virginia beach"
trumpilot$subregion[trumpilot$subregion=="yellowstone"]<-"yellowstone national"
trumpilot$subregion<-str_remove(trumpilot$subregion,"\\.")

counties<-counties %>% mutate(subregion=trimws(subregion), region=trimws(region), id=paste(region,subregion, sep="_"))
trumpilot<- trumpilot %>% mutate(subregion=trimws(subregion), region=trimws(region),id=paste(region, subregion, sep="_"))
mydata<-left_join(counties, trumpilot, by=c("region","subregion"))
mydata$soyval12[is.na(mydata$soyval12)]<-0

```

Plot soy data:

```{r}

#Sales USD
mydata$soy_scale<-0
mydata$soy_scale[mydata$sales_USD>=1000 & mydata$sales_USD<1595250]<-1
mydata$soy_scale[mydata$sales_USD>=1595250 & mydata$sales_USD<10285500]<-2
mydata$soy_scale[mydata$sales_USD>=10285500 & mydata$sales_USD<33130500]<-3
mydata$soy_scale[mydata$sales_USD>=33130500 ]<-4
mydata$soy_scale<-factor(mydata$soy_scale, ordered=TRUE)

p <- ggplot() +
  geom_polygon(data=mydata, aes(x=long, y=lat, group=group, fill=soy_scale),color="gray",  size=.0001) +
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())+
   					 theme(legend.position="bottom") +
  scale_fill_brewer(name="Soy Sales, USD:", palette="Reds", labels=c("none","<25st pctl","< median","< 75 pctl","> 75 pctl")) +guides(fill=guide_legend(nrow=2, title.position="top"))

p +coord_map("albers",lat0=39, lat1=45)

ggsave("soybean_map1.pdf")




#Production, bushels:
mydata$soy_scale1<-0
mydata$soy_scale1[mydata$prod_bush>=62 & mydata$prod_bush<105242]<-1
mydata$soy_scale1[mydata$prod_bush>=105242 & mydata$prod_bush<703941]<-2
mydata$soy_scale1[mydata$prod_bush>=703941 & mydata$prod_bush<2339635]<-3
mydata$soy_scale1[mydata$prod_bush>=2339635 ]<-4
mydata$soy_scale1<-factor(mydata$soy_scale1, ordered=TRUE)

p <- ggplot() +
  geom_polygon(data=mydata, aes(x=long, y=lat, group=group, fill=soy_scale1),color="gray",  size=.0001) +
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())+
   					 theme(legend.position="bottom") +
  scale_fill_brewer(name="Soy Production, bushels:", palette="Reds", labels=c("none","<25st pctl","< median","< 75 pctl","> 75 pctl")) +guides(fill=guide_legend(nrow=2, title.position="top"))

p +coord_map("albers",lat0=39, lat1=45)

ggsave("soybean_map2.pdf")

#Harvested, acres:
mydata$soy_scale2<-0
mydata$soy_scale2[mydata$soyarea>=6 & mydata$soyarea<2959]<-1
mydata$soy_scale2[mydata$soyarea>=2959 & mydata$soyarea<18925]<-2
mydata$soy_scale2[mydata$soyarea>=18925 & mydata$soyarea<66223]<-3
mydata$soy_scale2[mydata$soyarea>=66223 ]<-4
mydata$soy_scale2<-factor(mydata$soy_scale2, ordered=TRUE)

p <- ggplot() +
  geom_polygon(data=mydata, aes(x=long, y=lat, group=group, fill=soy_scale2),color="gray",  size=.0001) +
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())+
   					 theme(legend.position="bottom") +
  scale_fill_brewer(name="Soy Area, acres:", palette="Reds", labels=c("none","<25st pctl","< median","< 75 pctl","> 75 pctl")) +guides(fill=guide_legend(nrow=2, title.position="top"))

p +coord_map("albers",lat0=39, lat1=45)

ggsave("soybean_map3.pdf")

#Sales as a percent of GDP
mydata$soy_scale3<-0
mydata$soy_scale3[mydata$soyval12v1>0 & mydata$soyval12v1<0.15876 & !is.na(mydata$soyval12v1)]<-1
mydata$soy_scale3[mydata$soyval12v1>=0.15876 & mydata$soyval12v1<0.92373 & !is.na(mydata$soyval12v1)]<-2
mydata$soy_scale3[mydata$soyval12v1>=0.92373 & mydata$soyval12v1<5.03303 & !is.na(mydata$soyval12v1)]<-3
mydata$soy_scale3[mydata$soyval12v1>=5.03303 & !is.na(mydata$soyval12v1)]<-4
mydata$soy_scale3<-factor(mydata$soy_scale3, ordered=TRUE)

p <- ggplot() +
  geom_polygon(data=mydata, aes(x=long, y=lat, group=group, fill=soy_scale3),color="gray",  size=.0001) +
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())+
   					 theme(legend.position="bottom") +
  scale_fill_brewer(name="Soy Sales,% GDP:", palette="Reds", labels=c("none","<25st pctl","< median","< 75 pctl","> 75 pctl")) +guides(fill=guide_legend(nrow=2, title.position="top"))

p +coord_map("albers",lat0=39, lat1=45)

ggsave("soybean_map4.pdf")


```

Plot change in Rep votes:

```{r}

mydata$votech2<-NA
mydata$votech2[exp(mydata$votech)<0.9]<-1
mydata$votech2[exp(mydata$votech)>=0.9 & exp(mydata$votech)<.95]<-2
mydata$votech2[exp(mydata$votech)>=0.95 & exp(mydata$votech)<.99]<-3
mydata$votech2[exp(mydata$votech)>=0.99 & exp(mydata$votech)<1]<-4
mydata$votech2[exp(mydata$votech)==1  ]<-5
mydata$votech2[exp(mydata$votech)>1 & exp(mydata$votech)<1.01]<-6
mydata$votech2[exp(mydata$votech)>=1.01 & exp(mydata$votech)<1.05]<-7
mydata$votech2[exp(mydata$votech)>=1.05 & exp(mydata$votech)<1.1]<-8
mydata$votech2[exp(mydata$votech)>=1.1 ]<-9
mydata$votech2<-factor(mydata$votech2, ordered=TRUE)




p1 <- ggplot() +
  geom_polygon(data=mydata, aes(x=long, y=lat, group=group, fill=votech2), colour="gray") +
  geom_path(data=states, aes(x=long, y=lat, group=group), color="black")+
  theme(axis.text=element_blank(),
              axis.ticks=element_blank(),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank())+
   					 theme(legend.position="bottom") +
  scale_fill_brewer(name="Vote Change:", palette="RdBu",direction=-1,labels=c(">10% Dem",">5% Dem",">1% Dem","<1% Dem","No Change/NA","<1% Rep","<5% Rep","<10% Rep",">10% Rep")) +guides(fill=guide_legend(nrow=3, title.position="top"))

p1+coord_map("albers",lat0=39, lat1=45)



ggsave("map_votech.pdf")


```
Scatterplots:
```{r}
#Sales, USD:
#Set theme options:
library(scales)
library(ggrepel)

theme_set(theme_grey() + theme(panel.background = element_rect(fill = NA, color = 'black'))+ theme(axis.text=element_text(size=10),
					axis.title=element_text(size=12,face="bold")))


trumpilot$mylabel<-trumpilot$state
trumpilot$mylabel[trumpilot$sales_USD<100000000]<-""
p<-ggplot(data=filter(trumpilot, is.finite(votech) & sales_USD>0), aes(x=sales_USD/1000000, y=votech, label=mylabel))+geom_point()+
                geom_text_repel()+
							 geom_smooth(method=lm) +scale_y_continuous("Vote Change, logged", limits=c(-1,1)) + scale_x_continuous("Soy Sales, millions USD")
p

ggsave("sales_scatter.pdf")

#Bushels:
trumpilot$mylabel<-trumpilot$state
trumpilot$mylabel[trumpilot$prod_bush<10000000]<-""
p<-ggplot(data=filter(trumpilot, is.finite(votech) & prod_bush>0), aes(x=prod_bush/1000000, y=votech, label=mylabel))+geom_point()+
                geom_text_repel()+
							 geom_smooth(method=lm) +scale_y_continuous("Vote Change, logged", limits=c(-1,1)) + scale_x_continuous("Soy Production, millions of bushels")
p
ggsave("bushels_scatter.pdf")

#Acres,
trumpilot$mylabel<-trumpilot$state
trumpilot$mylabel[trumpilot$soyarea<200000]<-""
p<-ggplot(data=filter(trumpilot, is.finite(votech) & soyarea>0), aes(x=soyarea/100000, y=votech, label=mylabel))+geom_point()+
                geom_text_repel()+
							 geom_smooth(method=lm) +scale_y_continuous("Vote Change, logged", limits=c(-1,1)) + scale_x_continuous("Soy Area, 100 thousand acres")
p
ggsave("area_scatter.pdf")

#Sales, % GDP:
trumpilot$mylabel<-trumpilot$state
trumpilot$mylabel[trumpilot$soyval12v1<25]<-""
p<-ggplot(data=filter(trumpilot, is.finite(votech) & soyval12v1>0), aes(x=soyval12v1, y=votech, label=mylabel))+geom_point()+
              geom_text_repel()+
							 geom_smooth(method=lm) +scale_y_continuous("Vote Change, logged",  limits=c(-1,1)) + scale_x_continuous("Soy Sales, % GDP")
p

ggsave("salesGDP_scatter.pdf")


```

